framework:
    secret: '%env(APP_SECRET)%'

    session:
        handler_id: ~

    php_errors:
        log: true

    cache:

    assets:
        json_manifest_path: "%kernel.project_dir%/public/build/manifest.json"