version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    expose:
      - "5432"
    volumes:
      - huberisation_blog_db:/var/lib/postgresql/data
    networks:
      - web
    container_name: huberisation_db
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    links:
      - db
    expose:
      - "9000"
    depends_on:
      - db
    volumes:
      - app:/var/www/app
      - logs:/var/www/api/var/logs
    networks:
      - web
    container_name: huberisation_app
  web:
    build:
      context: ./webserver
      dockerfile: Dockerfile
    restart: always
    volumes:
      - app:/var/www/app
    ports:
      - 8080:80
    depends_on:
      - app
    links:
      - app
    networks:
      - web
      - default
    container_name: huberisation_web
    labels:
       - "traefik.backend=api_web"
       - "traefik.docker.network=web"
       - "traefik.enable=true"
       - "traefik.basic.frontend.rule=Host:${BACKEND_URL}"
       - "traefik.basic.port=80"
       - "traefik.basic.protocol=http"

volumes:
  app:
  logs:
  huberisation_blog_db:

networks:
  web:
    external: true